import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Button from '@/components/Button'
import Footer from '@/components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div className={styles.container}>
        <div className={styles.logo}>
          <Image src={'/images/twitterlogo.png'} alt="Twitter Logo" width={530} height={450} className={styles.twitterlogo}/>
        </div>
        <div className={styles.logincontainer}>
          <h1 className={styles.h1}>Happening now</h1>
          <h2 className={styles.h2}>Join today.</h2>
            <div className={styles.buttons}>
              <Button imgSrc='/images/googlelogo.png' imgSize="20px" title="Sign up with Google" border="1px solid var(--grey)"/>
              <Button imgSrc='/images/applelogo.png' imgSize="21px" title="Sign up with Apple"/>
            <div className={styles.orsection}>
              <hr className={styles.line}/>
              <span className={styles.or}>or</span>
              <hr className={styles.line}/>
            </div>
              <Button title="Create account" color="var(--blue)" textColor="var(--white)" className="bluehover"/>
              <p className={styles.p}>By signing up, you agree to the <a href="#" className={styles.linkblue}>Terms of Service </a> 
               and <a href="#" className={styles.linkblue}>Privacy Policy</a>, including <a href="#" className={styles.linkblue}>Cookie Use</a>
              </p>
              <h4 className={styles.h4}>Already have an account?</h4>
              <Button title="Sign in" color="var(--black)" textColor="var(--blue)" border="1px solid var(--grey)"/>
            </div>
            </div>
        </div>
      </main>
      <Footer/>
    </>
  )
}
